inherit_gem:
  renuocop: config/base.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - gemfiles/**/*
    - spec/dummy/db/schema.rb
    - spec/dummy/tmp/**/*

Style/ClassAndModuleChildren:
  Enabled: false
