development: &default
  adapter: sqlite3
  database: storage/development.sqlite3
  pool: <%= ENV.fetch "RAILS_MAX_THREADS", Concurrent.physical_processor_count %>
  timeout: 5000

test:
  <<: *default
  database: storage/test.sqlite3
