# frozen_string_literal: true

source "https://rubygems.org"

gem "hotsheet", path: "../.."
gem "importmap-rails"
gem "puma"
gem "rails", github: "rails/rails", branch: "main"
gem "sqlite3"
gem "turbo-rails"

group :development, :test do
  gem "better_errors"
  gem "binding_of_caller"
  gem "debug"
  gem "faker", require: false
  gem "renuocop", require: false
  gem "rspec-rails", require: false
end
