# frozen_string_literal: true

source "https://rubygems.org"

gem "hotsheet", path: "../.."
gem "puma"
gem "sqlite3"

group :test do
  gem "appraisal"
  gem "better_errors"
  gem "binding_of_caller"
  gem "capybara"
  gem "database_cleaner-active_record", require: false
  gem "debug"
  gem "faker", require: false
  gem "renuocop", require: false
  gem "rspec-rails"
  gem "selenium-webdriver", require: false
end
